name: books_finder
description: A library to help on the search for books on google books api
version: 4.1.0
repository: https://github.com/bdlukaa/books_finder

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.12.2

dev_dependencies:
  test: ^1.16.8
